FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

RUN rm -rf dist node_modules
RUN npm ci

COPY . .

ENV DATABASE_URL="postgresql://dummy:5432/dummy"
RUN npx prisma generate
RUN npm run build

FROM node:22-alpine

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/prisma.config.ts ./


EXPOSE 3000

CMD [ "npm", "run", "start:prod" ]
